### ISSUE TITLE
Base Meta Tags module

### ISSUE THREAD

**Issue by findlabnet** [backdrop-ops/contrib#112]
Hello, 
here is first public release of very simple [module] (https://github.com/findlabnet/base_meta).
I hope it can be useful for someone.
Thanks.

**Comment by klonos** [comment]
Hey there @findlabnet! Thanx for the module. You can apply for contrib membership and move this project to the official Backdrop contrib repo. This way it will also show up in the list of available modules in backdropcms.org as well in the coming Project Browser within all Backdrop installations.

[How to apply](https://github.com/backdrop-ops/contrib)
[New project checklist section](https://github.com/backdrop-ops/contrib#new-project-checklist)

Do let us know if you need any help or clarifications along the way.

**Comment by findlabnet** [comment]
So, I've open this issue with link to a project. What is a next step on this way?

**Comment by quicksketch** [comment]
Hi @findlabnet! Thanks for creating this new module! We'd be thrilled to have it in the Backdrop Contrib repository. It looks like this is a new module from scratch, is that correct? If so, then we can skip the requirement that you maintain the history from Drupal 7.

On a quick read, I ran across one issue that `hook_config_info()` defines `base_meta.second_set_of.settings` as a config file, but that doesn't exist. Perhaps just some debugging code that hadn't been cleaned up?

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2). (Not applicable in this case.)

You're meeting all the immediate requirements however. I've sent an invitation to you to join the Contrib group. You can then transfer the project to the `backdrop-contrib` group. When you think the project is ready for public use, please make a tag and official release on GitHub to get the project listed under http://backdropcms.org/modules. Thanks and welcome!

**Comment by quicksketch** [comment]
Invitation has been sent, let me know if you have any questions. Welcome again!

**Comment by findlabnet** [comment]
Hi @quicksketch! Thanks for invitation!
I need some help: by mistake I've added extra group as owners to [repo](https://github.com/backdrop-contrib/base_meta) when transfer it to `backdrop-contrib` - as result cannot set default branch (I think insufficient permissions). Can you fix it please, e.g. remove this group  from owners?
Thank you!

**Comment by quicksketch** [comment]
Hi @findlabnet! I think I fixed it. I've added you as an owner of the repository, so you should be able to add/remove collaborators on your own now, as well as set the default branch.

**Comment by findlabnet** [comment]
Thank you @quicksketch! Yes it fixed!
